logging:
    level:
        org:
            springframework:
                security: DEBUG
server:
    servlet:
        context-path: /msapi
    tomcat:
        relaxed-query-chars: '|,{,},[,]'
spring:
    cloud:
        consul:
            discovery:
                health-check-path: /msapi/actuator/health
    datasource:
        url: jdbc:mysql://172.18.0.2:3306/test?useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
management:
    endpoint:
        metrics:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    security:
        enabled: false