patient:
  rest:
    username: testadmin04
    password: testadmin04#
logging:
    level:
        org:
            springframework:
                security: DEBUG
server:
    servlet:
        context-path: /msapi
    port: 8087
    tomcat:
        relaxed-query-chars: '|,{,},[,]'
spring:
    cloud:
        consul:
            discovery:
                health-check-path: /msapi/actuator/health
            host: localhost
            port: 8500
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        password: mysql2010
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
management:
    endpoint:
        metrics:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    security:
        enabled: false
