spring:
    datasource:
        password: mysql2010
        username: root
    cache:
        redis:
            cache-null-values: false
            time-to-live: 200000
            use-key-prefix: false
        type: redis
server:
    port: 8080