spring:
    datasource:
        password: ${dbpassword}
        username: ${username}
    cache:
        redis:
            cache-null-values: false
            time-to-live: 200000
            use-key-prefix: false
        type: redis
    redis:
        host: host.docker.internal
        port: 6379
server:
    port: 8080